version: '3.4'

services:
  db:
    image: mysql:5.7.22
    command: mysqld --default_authentication_plugin=mysql_native_password
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - 3308:3306
    networks:
      - wordpress-network

  wordpress:
    image: wordpress:latest
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html
    restart: always
    env_file:
      - ./config/wp.env
    ports:
      - 8000:80
    networks:
      - wordpress-network

volumes:
  db_data: {}

networks:
    wordpress-network:
      driver: bridge
