apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-hello-world
  template:
    metadata:
      labels:
        app: my-hello-world
    spec:
      containers:
      - name: my-hello-world
        image: aohana/my-hello-world:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-hello-world
spec:
  selector:
    app: my-hello-world
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
