version: '3.4'

services:
  db: 
    build: ./mysql/
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - dockercompose
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql
  
  backend:
    depends_on:
      - db
    build: ./flask/
    restart: always
    ports:
      - "5000:5000"
    networks:
      - dockercompose
    volumes:
      - ./flask:/app

networks:
  dockercompose:
